### ISSUE TITLE
add `/clients`

### ISSUE THREAD

**Issue by flexbox** [flexbox/weshipit.today#18]
As a client new lead
I can see the client list
So that it builds trust in the company

---

- [x]  Copy the content from [https://www.planetargon.com/clients](https://www.planetargon.com/clients)
- [x]  Add prismic

```
interface Client {
  id: id // type random
  name: string
  logo: file // .svg
  isVisibleHomepage: boolean
}
```

- [ ]  add .env [https://vercel.com/docs/concepts/projects/environment-variables](https://vercel.com/docs/concepts/projects/environment-variables)

**Add a section** 
https://missionctrl.dev/ have a nice approach with this tools

**Comment by flexbox** [comment]
## Phase 2

- [ ] feed database with clients from https://www.linkedin.com/in/david-leuliette/
- [ ] add to the homepage 4 clients like this
<img width="1461" alt="image" src="https://user-images.githubusercontent.com/360936/195374643-7a26dd9f-3db1-44bc-a360-96a7ff93a98a.png">
- [ ] add a link to `/clients`

https://www.planetargon.com/

on `clients`

- [ ] add a call to action Button like on the homepage

**Comment by MatthysDev** [comment]
<img width="186" alt="Capture d’écran 2022-10-28 à 11 24 03" src="https://user-images.githubusercontent.com/81434852/198553411-99abc012-5967-41b5-bb31-a6a707455863.png">
