### ISSUE TITLE
run test on every PR

### ISSUE THREAD

**Issue by flexbox** [flexbox/weshipit.today#50]
As a developer
I can have feedback when my PR is opened
So that I do not merge broken monorepo

---

**Context**
with https://github.com/flexbox/weshipit.today/pull/46 we introduced a broken `yarn start`
we want to avoid that in the future

**Solution**
with a github action we should run `yarn test`

- [ ] add a github action for every pull request
- [ ] run `yarn test`

**Comment by MatthysDev** [comment]
Can't be done  #73
