### ISSUE TITLE
SEO phase 2

### ISSUE THREAD

**Issue by flexbox** [flexbox/weshipit.today#57]
**Is your feature request related to a problem? Please describe.**
add SEO props like https://davidl.fr/

**Additional context**
- [x] Create an account on https://surferseo.com/

**Comment by MatthysDev** [comment]
Current surferseo : 
<img width="350" alt="Capture d’écran 2022-11-24 à 16 13 27" src="https://user-images.githubusercontent.com/81434852/203817204-b3bd6c60-2ccf-4fad-9768-9912571724ad.png">

**Comment by MatthysDev** [comment]
@flexbox need to have acces to weshipit google console
<img width="694" alt="Capture d’écran 2022-11-24 à 16 14 24" src="https://user-images.githubusercontent.com/81434852/203817411-ca22859a-0015-4284-827c-a61ccf2edf4b.png">

**Comment by flexbox** [comment]
@MatthysDev ✅ 
<img width="720" alt="image" src="https://user-images.githubusercontent.com/360936/203826698-22f8877d-de8c-4a96-a9a6-d086ceb621d7.png">

**Comment by flexbox** [comment]
user added to https://search.google.com/

**Comment by flexbox** [comment]
both Joined!
