### ISSUE TITLE
`react-native-tools`: filter by type

### ISSUE THREAD

**Issue by flexbox** [flexbox/weshipit.today#79]
- [x] fix responsive, you can use `grid` and `gap`
- [x] add arrow `>` from Heroicon

**Is your feature request related to a problem? Please describe.**
add navigation for topics

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/360936/210167539-f90c7bed-fb3f-42d8-9637-e0906f5f12b6.png)

**Comment by MatthysDev** [comment]
Need acces to airtable to do this
