### ISSUE TITLE
better homepage design 

### ISSUE THREAD

**Issue by flexbox** [flexbox/weshipit.today#92]
- [ ] Perhaps you could add some inline imagery? e.g. https://www.oishee.io/ 
- [ ] I'd decrease the font weight to 600 to make it easier to read.
- [ ] Increase the line height to 1.1 to aid readability.
- [ ] Change the colour of your Twitter links to blue to differentiate them from the other text and for consistency with your client link at the bottom of the page.
- [ ] Currently the client logos are different shades of grey. Suggest updating them to the same shade, preferably with at least 3:1 contrast ratio.
- [ ] I'd also add a line separator above the client logos. 
- [ ] Would be great to see some of your previous client work too.

**Comment by MatthysDev** [comment]
Done with #102
