### ISSUE TITLE
migrate `Text` component to `cva`

### ISSUE THREAD

**Issue by flexbox** [flexbox/weshipit.today#98]
As a dev
I can use `Text intent="h1" className="mp-12"`
So that I have the tailwind IntelliSense autocomplete

**Comment by MatthysDev** [comment]
I thinks its usefull when we only return <p>
<img width="330" alt="image" src="https://github.com/flexbox/weshipit.today/assets/81434852/25f609de-5fbc-499c-9d6b-3720356bc615">
